/**
 * Autogenerated by Avro
 * 
 * DO NOT EDIT DIRECTLY
 */
package com.refactorlabs.cs378.assign6;  
@SuppressWarnings("all")
@org.apache.avro.specific.AvroGenerated
public enum CabStyle { 
  Sedan, Pickup, Wagon, Crew_Cab, NULL  ;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"enum\",\"name\":\"CabStyle\",\"namespace\":\"com.refactorlabs.cs378.assign6\",\"symbols\":[\"Sedan\",\"Pickup\",\"Wagon\",\"Crew_Cab\",\"NULL\"]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }
}
