/**
 * Autogenerated by Avro
 * 
 * DO NOT EDIT DIRECTLY
 */
package com.refactorlabs.cs378.assign6;  
@SuppressWarnings("all")
@org.apache.avro.specific.AvroGenerated
public enum ConditionType { 
  New, Used, NULL  ;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"enum\",\"name\":\"ConditionType\",\"namespace\":\"com.refactorlabs.cs378.assign6\",\"symbols\":[\"New\",\"Used\",\"NULL\"]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }
}
