/**
 * Autogenerated by Avro
 * 
 * DO NOT EDIT DIRECTLY
 */
package com.refactorlabs.cs378.assign6;  
@SuppressWarnings("all")
@org.apache.avro.specific.AvroGenerated
public enum EventSubtype { 
  CONTACT_FORM, MARKET_REPORT, VEHICLE_HISTORY, BADGES, FEATURES, PHOTO_MODAL, ALTERNATIVES, CONTACT_BANNER, CONTACT_BUTTON, DEALER_PHONE, GET_DIRECTIONS, TEST_DRIVE, FORM_ERROR, FORM_SUCCESS  ;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"enum\",\"name\":\"EventSubtype\",\"namespace\":\"com.refactorlabs.cs378.assign6\",\"symbols\":[\"CONTACT_FORM\",\"MARKET_REPORT\",\"VEHICLE_HISTORY\",\"BADGES\",\"FEATURES\",\"PHOTO_MODAL\",\"ALTERNATIVES\",\"CONTACT_BANNER\",\"CONTACT_BUTTON\",\"DEALER_PHONE\",\"GET_DIRECTIONS\",\"TEST_DRIVE\",\"FORM_ERROR\",\"FORM_SUCCESS\"]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }
}
